### ISSUE TITLE
Getting "Not a valid object name origin/staging" error while using rubocop-changes version '0.7.0'

### ISSUE THREAD

**Issue by rafaelcdelgado** [fcsonline/rubocop-changes#9]
I having the same problem as https://github.com/fcsonline/rubocop-changes/issues/8

But the problem is I'm using rubocop-changes on GithubActions. 

Run `bundle exec rubocop-changes -b staging`
  
`fatal: Not a valid object name origin/staging`

Ruby: 2.7.6
Bundler version 2.3.16

In local, runs perfect.

**Comment by rafaelcdelgado** [comment]
I found the solutions...    If someone has the same issue can use this action...

```
name: Rubocop Changes Linter
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  rubocop:
    name: Rubocop Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rub Rubocop PR Changes Linter
        run: bundle exec rubocop-changes -b staging
```

**Comment by fcsonline** [comment]
Yep, I faced something similar in the past. The problem with `fetch-depth: 0` is that if your repo is quite big, it will take some extra time to download all the references. You can do it like this:

```
      - uses: actions/checkout@v3
        with:
          ref: staging
      - uses: actions/checkout@v3
```

With this, you will download `staging` branch and the current one and `rubocop-changes` will be able to compare them.
